language: python
# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

cache:
  - pip
  - apt

#compiler: gcc-4.8  # need c++11 support and open-mp
#dist: trusty

# safelist
# branches:
#   only:
#   - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8

env:
  global:
    - OMP_NUM_THREADS=2
    - CC=gcc-4.8
    - LD=gcc-4.8
    - TWINE_USERNAME=bwinkel
    # Note: TWINE_PASSWORD is set in Travis settings

python:
  - 3.5
  # - 3.6

# command to install dependencies
install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - gcc -v
  - gcc-4.8 -v
  - pip install -r pip-requirements-dev
  - pip install .

# command to run tests
script:
  - cd tests
  - nosetests
  - cd ..
  # - pip install cibuildwheel
  # - cibuildwheel --output-dir wheelhouse
after_success:
  - echo "TRAVIS_TAG" $TRAVIS_TAG
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python setup.py sdist
      python -m twine upload dist/*.tar.gz
    fi
